projects:
  graphql:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\pattern.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
