// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://pffeaxgw7bad5obxfhddq4k3rm.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ajhuqgbbbze3jkzknzps4jeawi",
    "aws_content_delivery_bucket": "app-20190510104907-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-2",
    "aws_content_delivery_url": "http://app-20190510104907-hostingbucket-dev.s3-website.eu-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-west-2:651abcd2-7d53-45b2-a6d7-7324f44dc1bf",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_8gec19OSF",
    "aws_user_pools_web_client_id": "3t5650b7jh6nev93h79988380l",
    "oauth": {},
    "aws_user_files_s3_bucket": "app4fd3bd165a5f4b1e8fb0c79f167a6567-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
